apiVersion: v1
kind: Namespace
metadata:
  name: chat-example
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chat-example
  namespace: chat-example
spec:
  selector:
    matchLabels:
      app: chat-example
  template:
    metadata:
      labels:
        app: chat-example
    spec:
      containers:
      - image: dirty49374/chat-example:latest
        name: chat-example
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chat-example
  namespace: chat-example
spec:
  selector:
    app: chat-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: chat-example
  annotations:
    external-dns.alpha.kubernetes.io/hostname: chat.<<<= domain >>>
    external-dns.alpha.kubernetes.io/target: www.<<<= domain >>>
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  tls:
    - hosts:
      - chat.<<<= domain >>>
  rules:
  - host: chat.<<<= domain >>>
    http:
      paths:
      - path: /
        backend:
          serviceName: chat-example
          servicePort: 80

